### ISSUE TITLE
Check between webpage and markdown

### ISSUE THREAD

**Issue by gdequeiroz** [rladies/rladies-metrics#2]
Check if there is any meetup listed in the [Current-Chapters.md](https://github.com/rladies/starter-kit/blob/master/Current-Chapters.md) that it is not listed in the webpage (rladies.org)

![image](https://user-images.githubusercontent.com/1934546/41387385-7ebf4ba0-6f3b-11e8-8501-ec2f014eec1d.png)

**Comment by anadiedrichs** [comment]
The link to Current-Chapters.md is broken. I only found a Current-Chapters.csv  file. 

Some observations that could help with the process:

* Twin Cities, Minnesota appears on the website but not on the CSV file.
* Leuven, Belgium seems to be misspelled on the website. 
* Natal, Brazil appears twice on the website.

**Comment by gdequeiroz** [comment]
@anadiedrichs We retired the `.md` file and we have been using the `.csv` one. This issue should be resolved with the new website @chucheria is working on (https://github.com/rladies/rladies-website). We also need help there. 🙏 
(I will close this issue)
